# Generated by Django 5.2 on 2025-04-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_appuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates whether this user is an organization manager.A manager by default has a read/update access over ressources', verbose_name='is manager'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Designates whether this user is an organization owner.A owner by default has a full access over his ressources', verbose_name='is owner'),
        ),
    ]
