# Generated by Django 5.2 on 2025-05-06 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_last_modified_organization_updated_at_and_more'),
        ('user', '0005_appuser_is_manager_alter_appuser_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='orgs',
            field=models.ManyToManyField(blank=True, null=True, to='organization.organization', verbose_name='organizations'),
        ),
    ]
