# Generated by Django 5.2 on 2025-05-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_appuser_can_be_accessed_by_appuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='orgs',
        ),
    ]
