# Generated by Django 5.2 on 2025-06-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_appuser_is_manager_remove_appuser_is_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_permissions',
        ),
    ]
