# Generated by Django 5.2 on 2025-06-18 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_appuser_groups_remove_appuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
