# Generated by Django 5.2 on 2025-06-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_appuser_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['email', 'first_name', 'last_name', 'is_active'], name='user_appuse_email_f04ca4_idx'),
        ),
    ]
