# Generated by Django 5.2 on 2025-06-12 04:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_alter_organization_owner'),
        ('perms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='perms',
            field=models.TextField(verbose_name='Permissions'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicate a deleted ressource.Select this instead of deleting ressource.', verbose_name='deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('perms', models.TextField(verbose_name='Permissions')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the role')),
                ('description', models.TextField(verbose_name='Role description')),
                ('can_be_accessed_by', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_can_be_accessed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'unique_together': {('name', 'org')},
            },
        ),
    ]
