# Generated by Django 5.2 on 2025-06-25 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_department_created_at_and_more'),
        ('perms', '0004_alter_role_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='perms_role_name_e2a9f6_idx'),
        ),
    ]
