# Generated by Django 5.2 on 2025-05-12 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='owned_by_org', to='organization.department', verbose_name='organization departments'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='organization members'),
        ),
    ]
