# Generated by Django 5.2 on 2025-05-06 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='last_modified',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='organization',
            name='can_be_accessed_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_can_be_accessed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(default='', verbose_name='organization description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicate a deleted ressource.Select this instead of deleting ressource.', verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_owner', to=settings.AUTH_USER_MODEL, verbose_name='organization owner'),
        ),
    ]
