# Generated by Django 5.2 on 2025-05-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_alter_organization_owner'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allowed_auto_status_update',
            field=models.BooleanField(default=True, help_text='Wether to automatically apply status update logic', verbose_name='Allowed status update'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'org')},
        ),
    ]
