# Generated by Django 5.2 on 2025-05-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('tasks', '0002_task_allowed_auto_status_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with the task', related_name='tasks', to='tags.tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
