# Generated by Django 5.2 on 2025-06-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_allowed_auto_status_update_task_allow_auto_status_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
    ]
