# Generated by Django 5.2 on 2025-06-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_parent_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='allow_auto_status_update',
        ),
    ]
