# Generated by Django 5.2 on 2025-05-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_tags_delete_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='allowed_auto_status_update',
            new_name='allow_auto_status_update',
        ),
    ]
