# Generated by Django 5.2 on 2025-06-25 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_department_created_at_and_more'),
        ('tags', '0002_alter_tag_created_at_tag_tags_tag_name_3fbe74_idx'),
        ('tasks', '0006_remove_task_allow_auto_status_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['name', 'priority', 'status', 'due_date', 'estimated_duration', 'actual_duration'], name='tasks_task_name_f4871d_idx'),
        ),
    ]
