# Generated by Django 5.2 on 2025-04-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('user', '0002_alter_appuser_managers_appuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Designates whether this user is an organization owner or not', verbose_name='is owner'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='orgs',
            field=models.ManyToManyField(to='organization.organization', verbose_name='organizations'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
    ]
