# Generated by Django 5.2 on 2025-05-07 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_appuser_created_by_alter_appuser_orgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
